num_char= len (input("What is your name ?"))
print("===============")
print(type(num_char))
print("===============")
new_num_char = str(num_char)
print(type(new_num_char))
print ("Your name has "+ new_num_char +" characters.")